sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite, otherSprite) {
    sprites.destroy(MRender)
    game.gameOver(false)
    game.setGameOverMessage(false, "GAME OVER!")
    game.reset()
})
let MRender: Sprite = null
scene.setBackgroundColor(2)
MRender = sprites.create(img`
    . . . . f f f f f f f f . . . . 
    . . . . f a 1 f f 1 a f . . . . 
    . . . . f 1 a f f a 1 f . . . . 
    . . . . f f f f f f f f . . . . 
    . f f f f f f f f f f f f f f . 
    . f f f f f f f f f f f f f f . 
    . f f f f f f f f f f f f f f . 
    . f f f f f f f f f f f f f f . 
    . f f f f f f f f f f f f f f . 
    . f f f f f f f f f f f f f a . 
    . a f a f f f f f f f f a f a . 
    . a a a f f f f f f f f a a a . 
    . . . . a f f f f f a a . . . . 
    . . . . a f f f f f a a . . . . 
    . . . . a f a a f a a a . . . . 
    . . . . a a a a a a a a . . . . 
    `, SpriteKind.Player)
controller.moveSprite(MRender)
let Menemy = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
Menemy.setVelocity(10, 27)
Menemy.setPosition(7, 108)
MRender.setVelocity(100, 100)
Menemy.follow(MRender)
